---
title: "Letras, palavras e verbos na música brasileira"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r, warning=FALSE}
library(tidyverse, warn.conflicts = F)
library(tidytext)
library(silgelib)
theme_set(theme_roboto())
```

```{r ler}
estilos = read_csv("artista_musica_estilo.txt", 
                   col_names = c("artista", "musica", "estilo"), 
                   col_types = "ccc") %>% 
    select(-musica)

word_averages = read_csv("word_stats-all.csv")
```

```{r limpar}
ignorar = c("repeat", "repete", "ltda", "lyrics", "instrumental", "repete", "edições", "musical", "musicais", "site", "oficial", "fonte", "intro", "refrão", "crédito", "enviado", "editora", "contribuição", "leandrostz", "mariano", "richards", "halen", "bernie", "taupin")

word_averages = word_averages %>% 
    filter(!(word %in% ignorar))

# Remover stop words
```

## Quais as palavras mais comuns?

Todos os estilos (menos gospel) juntos

```{r}
word_averages %>% 
    arrange(-number) %>% 
    head(50)
```

```{r}
word_averages %>% 
    ggplot(aes(x = number)) + 
    geom_freqpoly() + 
    scale_x_log10()

word_averages %>%
    filter(number >= 100) %>%
    ggplot(aes(x = median_position)) + 
    geom_histogram(bins = 20) + 
    scale_y_log10() # Estranho mas ajuda aqui

```

```{r}
word_averages %>%
  filter(number >= 50, 
         abs(median_position -.5) > .1, 
         abs(median_position -.5) < .40) %>%
  arrange(median_position)
```

## Por estilo

```{r}
word_averages_estilo = palavras %>%
    group_by(url_musica) %>%
    mutate(word_position = row_number() / n()) %>%
    ungroup() %>% 
    group_by(estilo, word) %>%
    summarize(median_position = median(word_position),
              ocorrencias = n(), 
              letras = n_distinct(url_musica))

write_csv(word_averages_estilo, "word_averages-estilos.csv")
```

```{r}
word_averages_estilo%>% 
    ungroup() %>% 
    group_by(estilo) %>% 
    top_n(5, letras)
    
```


```{r}
word_averages_estilo %>%
    filter(!(word %in% ignorar)) %>% 
    filter(letras >= 20, 
           abs(median_position -.5) > .1, 
           abs(median_position -.5) < .45) %>%
    arrange(median_position)
```

## Ela é, ele é ...

```{r}
bigrams <- as_letras %>%
    filter(estilo != "gospelreligioso") %>%
    select(url_musica, letra) %>%
    unnest_tokens(bigram, letra, token = "ngrams", n = 2, collapse = FALSE)

bigrams_separated <- bigrams %>%
    separate(bigram, c("word1", "word2"), sep = " ")
he_she_words <- bigrams_separated %>%
    filter(word1 %in% c("ele", "ela"))

he_she_words
```

```{r}
he_she_counts <- he_she_words %>%
    count(word1, word2) %>%
    spread(word1, n, fill = 0) %>%
    mutate(total = ele + ela,
           ele = (ele + 1) / sum(ele + 1),
           ela = (ela + 1) / sum(ela + 1),
           log_ratio = log2(ela / ele),
           abs_ratio = abs(log_ratio)) %>%
    filter(total > 50) %>% 
    arrange(desc(log_ratio))

he_she_counts
```

```{r}
trigrams <- as_letras %>%
    filter(estilo != "gospelreligioso") %>%
    select(url_musica, letra) %>%
    unnest_tokens(trigram, letra, token = "ngrams", n = 3, collapse = FALSE)

trigrams_separated <- trigrams %>%
    separate(trigram, c("word1", "word2", "word3"), sep = " ")
eles_sao_words <- trigrams_separated %>%
    filter(word1 %in% c("ele", "ela"), 
           word2 %in% c("é", "foi", "será", "seria"), 
           nchar(word3) > 3)

eles_sao_words

eles_sao_counts <- eles_sao_words %>%
    count(word1, word3) %>%
    spread(word1, n, fill = 0) %>%
    mutate(total = ele + ela,
           ele = (ele + 1) / sum(ele + 1),
           ela = (ela + 1) / sum(ela + 1),
           log_ratio = log2(ela / ele),
           abs_ratio = abs(log_ratio)) %>%
    filter(total > 5) %>% 
    arrange(desc(log_ratio))

eles_sao_counts

```

```{r}
eles_ambos_counts <- eles_sao_words %>%
    count(word1, word3) %>%
    spread(word1, n, fill = 0) %>%
    filter(ele > 0, ela > 0) %>% 
    mutate(total = ele + ela,
           ele = (ele + 1) / sum(ele + 1),
           ela = (ela + 1) / sum(ela + 1),
           log_ratio = log2(ela / ele),
           abs_ratio = abs(log_ratio)) %>%
    filter(total > 5) %>% 
    arrange(desc(log_ratio))

eles_ambos_counts
```

